# Generated by Django 6.0.1 on 2026-02-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título de la noticia', max_length=200)),
                ('fecha_publicacion', models.DateField(help_text='Fecha de publicación')),
                ('texto', models.TextField(help_text='Contenido completo de la noticia')),
            ],
            options={
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
