# Generated by Django 6.0.1 on 2026-02-01 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha_publicacion',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha de publicación'),
        ),
    ]
