# Generated by Django 6.0.1 on 2026-02-01 11:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_alter_noticia_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha_publicacion',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha en que se publica la noticia'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='texto',
            field=models.TextField(help_text='Contenido completo y detallado de la noticia'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(help_text='Encabezado de la noticia', max_length=200),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['-fecha_publicacion'], name='noticias_no_fecha_p_470f2b_idx'),
        ),
    ]
